version: "3"
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - ${NC_EXTERNAL_PORT}:80
    volumes:
      - ./logs:/var/log/apache2
    networks:
      - nt_systemlogs

networks:
  nt_systemlogs:
    name: nt_systemlogs