version: "3"
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - ${NC_EXTERNAL_PORT}:80
    volumes:
      - ./logs:/var/log/apache2
    networks:
      - logsystem_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - ${GF_EXTERNAL_PORT}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    networks:
      - logsystem_network

  loki:
    image: grafana/loki
    container_name: loki
    restart: always
    ports:
      - ${LK_EXTERNAL_PORT}:3100
    volumes:
      - ./loki:/mnt/config
    configs:
      - loki_config
    networks:
      - logsystem_network
    
  promtail: 
    image: grafana/promtail
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./logs:/var/nextcloud
    configs:
      - nextcloud_config
    external_links:
      - loki
    networks:
      - logsystem_network

configs:
  nextcloud_config:
    file: ./promtail/promtail-config.yaml
  loki_config:
    file: ./loki/loki-config.yaml

networks:
  nt_systemlogs:
    name: logsystem_network
